name: ci

#on: [push, pull_request]
on: [push]

jobs:
  unix:
    name: "${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: test
      run: ctest -V
    - name: install
      run: sudo make install

  windows:
    name: "${{ matrix.os }}: ${{ matrix.target }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest]
        target: ["Visual Studio 16 2019", "MSYS Makefiles"]
    env:
      MTARGET: "${{ matrix.target }}"

    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: cmake -G "${env:MTARGET}" .
        shell: pwsh
      - name: make
        run: cmake --build .
      - name: test
        run: ctest -V
